FROM debian:latest

# Mettre à jour les dépôts et installer les outils nécessaires
RUN apt update && apt upgrade -y && \
    apt install -y build-essential gdb cmake

# Créer le répertoire pour le code
WORKDIR /lfp_client

# Copier le contenu du dossier "ftp-compose" dans le conteneur
COPY app/. .

# Compiler le programme
RUN make

RUN echo "totototo" > toto.txt

# Lancer le programme avec les bons arguments
CMD ["./lfp", "lfp_server:8050", "-upload", "toto.txt"]
