services:
  lfp_server:
    build:
      context: .
      dockerfile: Dockerfile-server
    container_name: lfp_server
    ports:
      - "8050:8050"  # Hôte : Container
    expose:
      - "8050"

  lfp_client:
    build:
      context: .
      dockerfile: Dockerfile-client
    container_name: lfp_client